[advisories]
# Ignore known upstream issues so CI passes for the test‑net release.
# NOTE: These ignores are *temporary* — scheduled to be removed in v0.2.0
ignore = [
    # curve25519‑dalek timing leak (to be fixed when we move to 4.2.0)
    "RUSTSEC-2024-0344",
    # ed25519‑dalek oracle attack (to be fixed when we move to 2.2.0)
    "RUSTSEC-2022-0093"
]