[licenses]
allow = [
    "MIT",
    "Apache-2.0", 
    "BSD-3-Clause",
    "Unicode-3.0"
]

[advisories]
ignore = [
    "RUSTSEC-2024-0344", # curve25519-dalek timing leak
    "RUSTSEC-2022-0093", # ed25519-dalek oracle attack
]


[sources]
allow-git = [
    "https://github.com/twilight-project/zk-schnorr.git",
    "https://github.com/dalek-cryptography/bulletproofs.git",
]
