name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run fmt check
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build project
        run: cargo build --all-features

      - name: Run tests
        run: cargo test --all-features -- --nocapture

      - name: Check docs
        run: cargo doc --no-deps --document-private-items

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-audit & cargo-deny
        run: |
          cargo install cargo-audit
          cargo install cargo-deny

      - name: Run cargo audit
        run: cargo audit --deny warnings

      - name: Run cargo deny
        run: cargo deny check